'use client'

import React, { useEffect, useState } from 'react'
import { useParams } from 'next/navigation'
import { FileText, Globe, Loader2, ArrowLeft } from 'lucide-react'
import { Button } from '@/components/ui/button'
import Link from 'next/link'

export default function PublicDocPage() {
  const { slug } = useParams()
  const [doc, setDoc] = useState<any>(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    fetchDoc()
  }, [slug])

  const fetchDoc = async () => {
    try {
      const res = await fetch(`/api/docs/${slug}`)
      const data = await res.json()
      if (data.doc) setDoc(data.doc)
    } catch (err) {
      console.error('Fetch public doc error:', err)
    } finally {
      setLoading(false)
    }
  }

  if (loading) return (
    <div className="min-h-screen flex items-center justify-center bg-[#0A0A0A]">
      <Loader2 className="animate-spin text-primary size-8" />
    </div>
  )

  if (!doc) return (
    <div className="min-h-screen flex items-center justify-center bg-[#0A0A0A] text-white">
      This document is private or does not exist.
    </div>
  )

  return (
    <div className="min-h-screen bg-[#0A0A0A] text-zinc-300">
      <nav className="h-16 border-b border-white/5 px-6 flex items-center justify-between bg-[#0D0D0D]/50 backdrop-blur-xl fixed top-0 w-full z-50">
        <div className="flex items-center gap-4">
          <div className="size-8 rounded-lg bg-primary/20 flex items-center justify-center text-primary">
            <FileText size={16} />
          </div>
          <span className="text-xs font-bold text-white tracking-tight">Waterflow Documentation</span>
        </div>
        <Button variant="outline" className="rounded-xl border-white/10 hover:bg-white/5 text-[10px] font-bold uppercase tracking-widest" asChild>
          <Link href="/">Join Waterflow</Link>
        </Button>
      </nav>

      <main className="max-w-4xl mx-auto py-32 px-8 animate-in fade-in slide-in-from-bottom-8 duration-1000">
        <div className="mb-12 flex items-center gap-3">
          <Globe size={14} className="text-primary" />
          <span className="text-[10px] font-black uppercase tracking-widest text-zinc-500">Public Strategic Report • {doc.project_name}</span>
        </div>

        <h1 className="text-5xl font-black text-white mb-12 tracking-tight leading-tight">
          {doc.title}
        </h1>

        <div className="prose prose-invert max-w-none">
          {/* Simple markdown parsing if needed, but for now raw text with better formatting */}
          <div className="whitespace-pre-wrap leading-relaxed space-y-6 text-lg font-medium opacity-90">
            {doc.content}
          </div>
        </div>

        <footer className="mt-32 pt-12 border-t border-white/5 text-center">
          <p className="text-xs text-zinc-600">Generated by Waterflow AI • Collaborative Agency Suite</p>
        </footer>
      </main>
    </div>
  )
}
